name: notification_badge_plus
description: A Flutter plugin for displaying notification badges on app icons with comprehensive Android OEM support and iOS compatibility.
version: 1.0.0
homepage: https://github.com/durgeshparekh/notification_badge
repository: https://github.com/durgeshparekh/notification_badge
issue_tracker: https://github.com/durgeshparekh/notification_badge/issues
documentation: https://github.com/durgeshparekh/notification_badge#readme

topics:
  - notification
  - badge
  - android
  - ios
  - oem

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dp.notification_badge_plus
        pluginClass: NotificationBadgePlugin
      ios:
        pluginClass: NotificationBadgePlugin